version: "2"
services:
    kong-database:
        image: cassandra:2.2
    kong:
        image: kong
        depends_on:
            - kong-database
        links:
            - kong-database:kong-database
            - account:account
        environment:
            - "KONG_DATABASE=cassandra"
            - "KONG_CASSANDRA_CONTACT_POINTS=kong-database"
            - "KONG_PG_HOST=kong-database"
        ports:
            - 8000:8000
            - 8443:8443
            - 8001:8001
            - 7946:7946
            - 7946:7946/udp
    account:
        build: ./account
        ports:
            - 3000:3000
        links:
            - mongo:mongo
        depends_on:
            - mongo
    tweet:
        build: ./tweet
        ports:
            - 3001:3001
        links:
            - mongo:mongo
        depends_on:
            - mongo
    # client:
    #     build: ./client
    #     ports:
    #         - 5000:5000
    mongo:
        image: mongo
        ports:
            - 27017:27017
